name: Deploy  docker container
on:
  workflow_dispatch:

permissions:
  packages: read

jobs:
  deploy:
    runs-on: ec2-bice
    if: startsWith(github.ref, 'refs/tags')
    env: 
      GIT_USERNAME: ${{ github.actor }}
      GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository }}
      IMAGE_REGISTRY: ${{ 'https://ghcr.io' }}
      EXPOSE_PORT: ${{ secrets.EXPOSE_PORT || 8080 }} 
      PUBLISH_PORT: ${{ secrets.PUBLISH_PORT || 8081 }} 
      NAME_REPO: ${{ github.repository }}
      IMAGE_TAG: latest

    steps:
      - name: set up env var TAG image production
        run: |
          echo "IMAGE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
  
      - name: deploy in Docker
        run: |
          echo $GIT_PASSWORD | docker login $IMAGE_REGISTRY -u $GIT_USERNAME --password-stdin
          docker rm -f "$NAME_REPO"
          docker run -d --restart=unless-stopped --name "$NAME_REPO" -p "$PUBLISH_PORT:$EXPOSE_PORT" "$DOCKER_IMAGE_NAME:$IMAGE_TAG"
          echo "El container $NAME_REPO, se ejecuto correctamente"
          
