name: Manual Deploy by Tag
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy (e.g., v1.0.0)'
        required: true
permissions:
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      NOMBRE: ${{ vars.NOMBRE || 'nose' }}
    steps:
      - name: deploy in Docker
        run: echo $NOMBRE
